version: "3.9"
services:
  levoai-rabbitmq:
    image: 'rabbitmq:3.10.5-management'
    container_name: levoai-rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-levoai}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-levoailevoai}
      # send logs to stdout, ref: https://www.rabbitmq.com/logging.html#log-file-location
      RABBITMQ_LOGS: '-'

    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M

  levoai-satellite:
    image: 'levoai/satellite:${LEVOAI_SATELLITE_VERSION:-stable}'
    container_name: levoai-satellite
    restart: always
    ports:
      - '9999:9999'
    command:
      - "-w"
      - "1"
      - "-b"
      - "0.0.0.0:9999"
      - "--worker-class"
      - "gevent"
      - "--worker-connections"
      - "30"
      - "levoai_e7s.satellite.satellite:create_server()"
    environment:
      LEVOAI_DEBUG_ENABLED: ${LEVOAI_SATELLITE_DEBUG_ENABLED:-false}
      LEVOAI_DEBUG_PORT: ${LEVOAI_SATELLITE_DEBUG_PORT:-12345}
      LEVOAI_DEBUG_SERVER_HOST: ${LEVOAI_DEBUG_SERVER_HOST:-host.docker.internal}
      LEVOAI_MODE: docker-compose
      LEVOAI_LOG_LEVEL: ${LEVOAI_LOG_LEVEL:-INFO}
      LEVOAI_CONF_OVERRIDES: '{"onprem-api": {"url": "${LEVOAI_BASE_URL:-https://api.levo.ai}", "refresh-token": "${LEVOAI_AUTH_KEY}", "org-id": "${LEVOAI_ORG_ID:-}", "org-prefix": "${LEVOAI_ORG_PREFIX:-}"}}'
    depends_on:
      levoai-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 521M
        reservations:
          cpus: '0.30'
          memory: 256M

  levoai-tagger:
    image: 'levoai/satellite:${LEVOAI_SATELLITE_VERSION:-stable}'
    container_name: levoai-tagger
    restart: always
    entrypoint: ['python', '-OO']
    command:
      - /opt/levoai/e7s/src/python/levoai_e7s/tag_server.py
    environment:
      LEVOAI_DEBUG_ENABLED: ${LEVOAI_TAGGER_DEBUG_ENABLED:-false}
      LEVOAI_DEBUG_PORT: ${LEVOAI_TAGGER_DEBUG_PORT:-1234}
      LEVOAI_MODE: docker-compose
      LEVOAI_LOG_LEVEL: ${LEVOAI_LOG_LEVEL:-INFO}
      LEVOAI_DEBUG_SERVER_HOST: ${LEVOAI_DEBUG_SERVER_HOST:-host.docker.internal}
      PI_DETECTOR_DATA_DIR: /opt/levoai/datasets/
      LEVOAI_CONF_OVERRIDES: >
        {
          "onprem-api": {"url": "${LEVOAI_BASE_URL:-https://api.levo.ai}",
          "refresh-token": "${LEVOAI_AUTH_KEY}", "org-id": "${LEVOAI_ORG_ID:-}",
          "org-prefix": "${LEVOAI_ORG_PREFIX:-}"},
          "send_sample_payloads": "${LEVOAI_SEND_SAMPLE_PAYLOADS:-False}",
          "url_clusterer_id_len": "${LEVOAI_URL_CLUSTERER_ID_LEN:-1}",
          "max_samples_per_end_point": "${MAX_SAMPLES_PER_END_POINT:-2}",
          "min_urls_required_per_pattern": "${LEVOAI_MIN_URLS_PER_PATTERN:-10}",
          "dynamic_url_threshold_factor": "${DYNAMIC_URL_THRESHOLD_FACTOR:-0.5}",
          "cookie_auth_keys": "${LEVOAI_COOKIE_AUTH_KEYS:-}",
          "disable_ml_detector": "${LEVOAI_DISABLE_ML_DETECTOR:-true}",
          "service_naming": {"strategies": "HOST_HEADER,DEFAULT"},
          "user_resolvers": [{"name": "cookie_resolver", "type": "cookie", "key_names": ["PHPSESSID"]}],
          "users": {"testing_user": {"user_resolvers": ["cookie_resolver"],
                                     "cookies": {"PHPSESSID": "${LEVOAI_SAMPLES_USER:-}"}}},
          "tagger_batch_interval_minutes": ${LEVOAI_TAGGER_INTERVAL:-5}
        }
    depends_on:
      levoai-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '3.00'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 512M

  levoai-collector:
    image: 'levoai/collector:${LEVOAI_COLLECTOR_VERSION:-stable}'
    container_name: levoai-collector
    restart: always
    ports:
      - '4317:4317'
    depends_on:
      - levoai-satellite
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M
