const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');

const docsitems = [
  {
      label: "Getting Started",
      to: "docs/category/getting-started",
  },
  {
      label: "Satellite",
      to: "docs/satellite",
  },
  {
      label: "Sensor",
      to: "docs/sensor",
  },
  {
      label: "Levo CLI Reference",
      to: "tutorials/levo-cli-reference",
  },
  {
      label: "Integrations",
      to: "docs/integrations",
  },
  {
      label: "FAQs",
      to: "docs/faqs",
  },
]

const tutorialsitems = [
  {
      label: "Introduction to OWASP ZAP and Levo",
      to: "tutorials/zap-levo-addon",
  },
  {
      label: "API Observability with Levo",
      to: "tutorials/api-observability",
  }
]

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Levo.ai Documentation',
  tagline: 'Fully Automated API Security Testing in CI/CD',
  staticDirectories: ['static'],
  url: 'https://docs.levo.ai',
  baseUrl: '/',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',
  organizationName: 'levoai', // Usually your GitHub org/user name.
  projectName: 'docs', // Usually your repo name.
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  markdown: {
    mermaid: true,
  },
  themes: ["@docusaurus/theme-mermaid"],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: 'docs',
          editUrl:
            'https://github.com/levoai/docs/edit/main/',
        },
        blog: {
          showReadingTime: true,
          editUrl:
            'https://github.com/levoai/docs/edit/main/',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  plugins: [
    [
      require.resolve("@cmfcmf/docusaurus-search-local"),
      {
        indexDocSidebarParentCategories: 0
      }
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'tutorials',
        path: 'tutorials',
        routeBasePath: 'tutorials',
        editUrl:
          'https://github.com/levoai/docs/edit/main/',
      }
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'vulnerability-guide',
        path: 'vulnerability-guide',
        routeBasePath: 'vulnerability-guide',
        editUrl:
          'https://github.com/levoai/docs/edit/main/',
      }
    ]

  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: 'img/docusaurus-social-card.jpg',
      navbar: {
        title: 'Levo',
        logo: {
          alt: 'https://docs.levo.ai/img/logo.svg',
          src: 'img/logo.svg',
        },
        items: [
          {
            position: 'right',
            label: 'Docs',
            type: 'dropdown',
            to: '/docs/category/getting-started',
            items: docsitems,
            // sidebarID: 'AutogeneratedSidebar',
          },
          {
            position: 'right',
            label: 'Tutorials',
            type: 'dropdown',
            to: '/tutorials',
            items: tutorialsitems
          },
          {
            position: 'right',
            label: 'Vulnerability Guide',
            to: '/vulnerability-guide/guide',
          },
          {
            to: '/blog', 
            label: 'Blog', 
            position: 'right'
          },
          {
            href: 'https://github.com/levoai/docs',
            label: 'GitHub',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              {
                label: 'Tutorial',
                to: '/tutorials/',
              },
              {
                label: 'Docs',
                to: '/docs/',
              },
              {
                label: 'Blogs',
                to: '/blog/',
              },
            ],
          },
          {
            title: 'Community',
            items: [
              {
                label: 'Stack Overflow',
                href: 'https://stackoverflow.com/questions/tagged/docusaurus',
              },
              {
                label: 'Discord',
                href: 'https://discordapp.com/invite/docusaurus',
              },
              {
                label: 'Twitter',
                href: 'https://twitter.com/docusaurus',
              },
            ],
          },
          {
            title: 'More',
            items: [
              {
                label: 'Blog',
                to: '/blog',
              },
              {
                label: 'GitHub',
                href: 'https://github.com/facebook/docusaurus',
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Levo, Inc. Built with Docusaurus.`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    }),
};

module.exports = config;
