apiVersion: v1
kind: Service
metadata:
  name: { { include "docs.fullname" . } }
  labels:
    app: { { include "docs.name" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: { { include "docs.name" . } }
