---
sensor:
  imageRepo: docker.io/levoai/pcap-sensor
  imageTag: latest
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector: {}
  containerResources:
    requests:
      cpu: 0.1
      memory: 150Mi
    limits:
      cpu: 0.25
      memory: 200Mi
  config:
    satelliteUrl: "http://levoai-satellite:9999"
    levoEnv: "staging"
    traceExportInterval: "1.0"
    rateLimit: "100.0"
    maxHttpLength: "1000000"
    streamTimeoutSeconds: "2"
    levoaiOrgId: ""
    filter: ""
    hostAllow: ""
    pathAllow: ""
    hostExclusions: ""
    pathExclusions: ""
