replicaCount: 2

image:
  repository: ghcr.io/your-org/levo-docs
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: docs.dev.levo.ai
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: docs-tls
      hosts:
        - docs.dev.levo.ai

resources: {}
